# Generated by Django 5.1.7 on 2025-04-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktyor',
            name='davlat_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aktyor',
            name='davlat_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aktyor',
            name='davlat_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aktyor',
            name='ism_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aktyor',
            name='ism_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aktyor',
            name='ism_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='janr_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='janr_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='janr_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='nom_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kino',
            name='nom_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='nom_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='nom_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tarif',
            name='nom_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
